name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - develop
    exclude:
      - release/xyz	
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - master

pool: 
  name: linux-pool

variables:


parameters:
- name: env
  type: string
  default: dev
  values: 
    - dev
    - test
    - stage
