name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - develop
    exclude:
      - release/xyz	
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - master

pool: 
  name: linux-pool

variables:


parameters:
- name: env
  type: string
  default: dev
  values: 
    - dev
    - test
    - stage

stages:
- stage: Build
    displayName: Build Java
    jobs:
    - job: Build
    displayName: Build
    steps:	
    - checkout: self
    - task: Maven@3
      displayName: MavenBuild
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testResultsFiles: '**/TEST-*.xml' 
        searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
        mergeTestResults: false # Optional
        failTaskOnFailedTests: true  # Fail build if any t
        #testRunTitle: # Optional
        #buildPlatform: # Optional
        #buildConfiguration: # Optional
        #publishRunAttachments: true # Optional
        
    - task: Code analysis

    - task: Code analysis
    
    - task: Publish 
    
    - task: Functional testing 
    
    - task: API testing - postman/soap UI
    
    - task: Security Testing - ZAP
    
    - task: Performance Testing - JMeter
    
- stage: BuildDocker
    displayName: Build Docker Image 
    jobs:
    - job: BuildDocekr
    displayName: BuildDocker
    steps:	
    - checkout: self
    - task: Maven@3
    
    
    

    
    

    
               
